// Renders the generated tool reference of docs/mcp.md (see
// tools/generate-mcp-docs.mjs): one section per tool from its definition
// (packages/shared/src/mcp) and the JSON schema the server announces.

const cell = (text) => String(text).replaceAll("|", "\\|").replaceAll("\n", " ");
const code = (text) => `\`${text}\``;

function row(cells) {
  return `| ${cells.map(cell).join(" | ")} |`;
}

function table(head, rows) {
  return [row(head), row(head.map(() => "---")), ...rows.map(row)].join("\n");
}

function json(value) {
  return ["```json", JSON.stringify(value, null, 2), "```"].join("\n");
}

function range(min, max, unit) {
  if (min !== undefined && max !== undefined && max < Number.MAX_SAFE_INTEGER) {
    return `${min}-${max}${unit}`;
  }
  if (min !== undefined) return `≥ ${min}${unit}`;
  if (max !== undefined) return `≤ ${max}${unit}`;
  return "";
}

// A JSON schema property as a short type: "string (uuid)", "integer 1-10".
export function describeType(schema) {
  if (schema.anyOf) return schema.anyOf.map(describeType).join(" | ");
  if (schema.type === "null") return "null";
  if (schema.type === "string") {
    if (schema.format) return `string (${schema.format})`;
    const length = range(schema.minLength, schema.maxLength, " chars");
    return length ? `string, ${length}` : "string";
  }
  if (schema.type === "integer" || schema.type === "number") {
    const bounds = range(schema.minimum, schema.maximum, "");
    return bounds ? `${schema.type} ${bounds}` : schema.type;
  }
  return schema.type ?? "any";
}

function parameters(definition, inputSchema) {
  const properties = Object.entries(inputSchema.properties ?? {});
  if (properties.length === 0) return "None.";
  const required = new Set(inputSchema.required ?? []);
  const rows = properties.map(([name, schema]) => [
    code(name),
    describeType(schema),
    required.has(name) ? "yes" : "no",
    name in definition.defaults ? code(JSON.stringify(definition.defaults[name])) : "",
    schema.description ?? "",
  ]);
  return table(["Name", "Type", "Required", "Default", "Description"], rows);
}

function result(definition) {
  const rows = definition.result.map(([field, type, meaning]) => [code(field), type, meaning]);
  return table(["Field", "Type", "Meaning"], rows);
}

function errors(definition) {
  const own = definition.errors.map(([error, when]) => `- ${code(error)}: ${when}`);
  const common = "- the [common errors](#errors) every tool can return.";
  return [...own, common].join("\n");
}

function kind(definition) {
  if (definition.readOnly) return "read-only";
  return definition.destructive ? "moves to the trash" : "writes";
}

// First sentence of the description for the summary table; two when the
// first is a mere "Start here."
function summary(description) {
  const ends = [...description.matchAll(/\.(\s|$)/g)].map((match) => match.index + 1);
  const end = ends.find((index) => index >= 30) ?? description.length;
  return description.slice(0, end);
}

function toolSection(definition, listed) {
  return [
    `### ${code(definition.name)}`,
    `**${definition.title}** · permission ${code(definition.permission)} · ${kind(definition)}`,
    listed.description,
    "**Parameters**",
    parameters(definition, listed.inputSchema),
    "**Result**",
    result(definition),
    "**Errors**",
    errors(definition),
    "**Example**: arguments",
    json(definition.example.arguments),
    "and result",
    json(definition.example.result),
  ].join("\n\n");
}

// The generated block, without its markers. `listed` holds each tool as
// tools/list announces it (name, description, inputSchema).
export function renderToolReference(definitions, listed, commonErrors) {
  const byName = new Map(listed.map((tool) => [tool.name, tool]));
  const overview = table(
    ["Tool", "Permission", "Kind", "Purpose"],
    definitions.map((definition) => [
      `[${code(definition.name)}](#${definition.name})`,
      code(definition.permission),
      kind(definition),
      summary(byName.get(definition.name).description),
    ]),
  );
  const common = commonErrors.map(([error]) => code(error)).join(", ");
  return [
    "<!-- Generated by tools/generate-mcp-docs.mjs from packages/shared/src/mcp. " +
      "Do not edit by hand: change the definitions, then run `pnpm docs:mcp`. -->",
    overview,
    "Results are JSON objects, sent as the text content of the tool result. Failures " +
      "set `isError` and send `{ error, message, ...details }` (see [Errors](#errors)). " +
      `Every tool can also fail with the common errors ${common}.`,
    ...definitions.map((definition) => toolSection(definition, byName.get(definition.name))),
  ].join("\n\n");
}
